name       : yajl
version    : 2.1.0
release    : 1
source     :
    - https://github.com/lloyd/yajl/archive/2.1.0.tar.gz : 3fb73364a5a30efe615046d07e6db9d09fd2b41c763c5f7d3bfb121cd5c5ac5a
license    : ISC
summary    : YAJL
description: |
    A fast streaming JSON parsing library in C.
builddeps  :
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
